mandatory flags

diff --git a/.github/workflows/workflow-dispatcher.yml b/.github/workflows/workflow-dispatcher.yml
--- a/.github/workflows/workflow-dispatcher.yml
+++ b/.github/workflows/workflow-dispatcher.yml
@@ -20,10 +20,14 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Check valid environment
-        if: ${{ contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }} 
-        run: echo "Hello ${{ inputs.env }}"
-
       - name: Invalid environment
         if: ${{ !contains(fromJson('["dv01", "dv02","dv03","dv04","dv05"]'), inputs.env) }} 
-        run: echo "Invalid environment"
+        run: |
+        echo "Invalid environment"
+        exit 1
+
+      - name: Validate deployment type
+        if: ${{ !inputs.Backfill && !inputs.Main}}  
+        run: |
+        echo "Select either Backfill or main"
+        exit 1
